/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/router';
import * as import3 from '@angular/common';
import * as import4 from '../../../src/app/route-application/route-application.module';
import * as import5 from '@angular/platform-browser';
import * as import6 from '@angular/forms';
import * as import7 from '@angular/http';
import * as import8 from './app.component.ngfactory';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _ɵa_0:any;
  _ErrorHandler_1:any;
  _ɵg_2:import2.ɵg;
  _NgProbeToken_3:any[];
  _APP_INITIALIZER_4:any[];
  _ApplicationInitStatus_5:import0.ApplicationInitStatus;
  _ɵf_6:import0.ɵf;
  _ApplicationRef_7:any;
  _UrlSerializer_8:import2.DefaultUrlSerializer;
  _RouterOutletMap_9:import2.RouterOutletMap;
  _ROUTER_CONFIGURATION_10:any;
  _LocationStrategy_11:any;
  _Location_12:import3.Location;
  _Compiler_13:import0.Compiler;
  _NgModuleFactoryLoader_14:import0.SystemJsNgModuleLoader;
  _ROUTES_15:any[];
  _Router_16:any;
  _RouterModule_17:import2.RouterModule;
  _RouteApplicationModule_18:import4.RouteApplicationModule;
  _CommonModule_19:import3.CommonModule;
  _ApplicationModule_20:import0.ApplicationModule;
  _BrowserModule_21:import5.BrowserModule;
  _ɵba_22:import6.ɵba;
  _FormsModule_23:import6.FormsModule;
  _HttpModule_24:import7.HttpModule;
  _AppModule_25:import1.AppModule;
  __ActivatedRoute_26:any;
  __NoPreloading_27:import2.NoPreloading;
  __PreloadingStrategy_28:any;
  __RouterPreloader_29:import2.RouterPreloader;
  __PreloadAllModules_30:import2.PreloadAllModules;
  __ROUTER_INITIALIZER_31:any;
  __APP_BOOTSTRAP_LISTENER_32:any[];
  __LOCALE_ID_33:any;
  __NgLocalization_34:import3.NgLocaleLocalization;
  __APP_ID_35:any;
  __IterableDiffers_36:any;
  __KeyValueDiffers_37:any;
  __DomSanitizer_38:import5.ɵe;
  __Sanitizer_39:any;
  __HAMMER_GESTURE_CONFIG_40:import5.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_41:any[];
  __EventManager_42:import5.EventManager;
  __ɵDomSharedStylesHost_43:import5.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_44:import5.ɵDomRendererFactory2;
  __RendererFactory2_45:any;
  __ɵSharedStylesHost_46:any;
  __Testability_47:import0.Testability;
  __Meta_48:import5.Meta;
  __Title_49:import5.Title;
  __ɵi_50:import6.ɵi;
  __BrowserXhr_51:import7.BrowserXhr;
  __ResponseOptions_52:import7.BaseResponseOptions;
  __XSRFStrategy_53:any;
  __XHRBackend_54:import7.XHRBackend;
  __RequestOptions_55:import7.BaseRequestOptions;
  __Http_56:any;
  constructor(parent:import0.Injector) {
    super(parent,[import8.AppComponentNgFactory],[import8.AppComponentNgFactory]);
  }
  get _ActivatedRoute_26():any {
    if ((this.__ActivatedRoute_26 == null)) { (this.__ActivatedRoute_26 = import2.ɵf(this._Router_16)); }
    return this.__ActivatedRoute_26;
  }
  get _NoPreloading_27():import2.NoPreloading {
    if ((this.__NoPreloading_27 == null)) { (this.__NoPreloading_27 = new import2.NoPreloading()); }
    return this.__NoPreloading_27;
  }
  get _PreloadingStrategy_28():any {
    if ((this.__PreloadingStrategy_28 == null)) { (this.__PreloadingStrategy_28 = this._NoPreloading_27); }
    return this.__PreloadingStrategy_28;
  }
  get _RouterPreloader_29():import2.RouterPreloader {
    if ((this.__RouterPreloader_29 == null)) { (this.__RouterPreloader_29 = new import2.RouterPreloader(this._Router_16,this._NgModuleFactoryLoader_14,this._Compiler_13,this,this._PreloadingStrategy_28)); }
    return this.__RouterPreloader_29;
  }
  get _PreloadAllModules_30():import2.PreloadAllModules {
    if ((this.__PreloadAllModules_30 == null)) { (this.__PreloadAllModules_30 = new import2.PreloadAllModules()); }
    return this.__PreloadAllModules_30;
  }
  get _ROUTER_INITIALIZER_31():any {
    if ((this.__ROUTER_INITIALIZER_31 == null)) { (this.__ROUTER_INITIALIZER_31 = import2.ɵi(this._ɵg_2)); }
    return this.__ROUTER_INITIALIZER_31;
  }
  get _APP_BOOTSTRAP_LISTENER_32():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_32 == null)) { (this.__APP_BOOTSTRAP_LISTENER_32 = [this._ROUTER_INITIALIZER_31]); }
    return this.__APP_BOOTSTRAP_LISTENER_32;
  }
  get _LOCALE_ID_33():any {
    if ((this.__LOCALE_ID_33 == null)) { (this.__LOCALE_ID_33 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_33;
  }
  get _NgLocalization_34():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_34 == null)) { (this.__NgLocalization_34 = new import3.NgLocaleLocalization(this._LOCALE_ID_33)); }
    return this.__NgLocalization_34;
  }
  get _APP_ID_35():any {
    if ((this.__APP_ID_35 == null)) { (this.__APP_ID_35 = import0.ɵg()); }
    return this.__APP_ID_35;
  }
  get _IterableDiffers_36():any {
    if ((this.__IterableDiffers_36 == null)) { (this.__IterableDiffers_36 = import0.ɵl()); }
    return this.__IterableDiffers_36;
  }
  get _KeyValueDiffers_37():any {
    if ((this.__KeyValueDiffers_37 == null)) { (this.__KeyValueDiffers_37 = import0.ɵm()); }
    return this.__KeyValueDiffers_37;
  }
  get _DomSanitizer_38():import5.ɵe {
    if ((this.__DomSanitizer_38 == null)) { (this.__DomSanitizer_38 = new import5.ɵe(this.parent.get(import5.DOCUMENT))); }
    return this.__DomSanitizer_38;
  }
  get _Sanitizer_39():any {
    if ((this.__Sanitizer_39 == null)) { (this.__Sanitizer_39 = this._DomSanitizer_38); }
    return this.__Sanitizer_39;
  }
  get _HAMMER_GESTURE_CONFIG_40():import5.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_40 == null)) { (this.__HAMMER_GESTURE_CONFIG_40 = new import5.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_40;
  }
  get _EVENT_MANAGER_PLUGINS_41():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_41 == null)) { (this.__EVENT_MANAGER_PLUGINS_41 = [
      new import5.ɵDomEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵKeyEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵHammerGesturesPlugin(this.parent.get(import5.DOCUMENT),this._HAMMER_GESTURE_CONFIG_40)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_41;
  }
  get _EventManager_42():import5.EventManager {
    if ((this.__EventManager_42 == null)) { (this.__EventManager_42 = new import5.EventManager(this._EVENT_MANAGER_PLUGINS_41,this.parent.get(import0.NgZone))); }
    return this.__EventManager_42;
  }
  get _ɵDomSharedStylesHost_43():import5.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_43 == null)) { (this.__ɵDomSharedStylesHost_43 = new import5.ɵDomSharedStylesHost(this.parent.get(import5.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_43;
  }
  get _ɵDomRendererFactory2_44():import5.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_44 == null)) { (this.__ɵDomRendererFactory2_44 = new import5.ɵDomRendererFactory2(this._EventManager_42,this._ɵDomSharedStylesHost_43)); }
    return this.__ɵDomRendererFactory2_44;
  }
  get _RendererFactory2_45():any {
    if ((this.__RendererFactory2_45 == null)) { (this.__RendererFactory2_45 = this._ɵDomRendererFactory2_44); }
    return this.__RendererFactory2_45;
  }
  get _ɵSharedStylesHost_46():any {
    if ((this.__ɵSharedStylesHost_46 == null)) { (this.__ɵSharedStylesHost_46 = this._ɵDomSharedStylesHost_43); }
    return this.__ɵSharedStylesHost_46;
  }
  get _Testability_47():import0.Testability {
    if ((this.__Testability_47 == null)) { (this.__Testability_47 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_47;
  }
  get _Meta_48():import5.Meta {
    if ((this.__Meta_48 == null)) { (this.__Meta_48 = new import5.Meta(this.parent.get(import5.DOCUMENT))); }
    return this.__Meta_48;
  }
  get _Title_49():import5.Title {
    if ((this.__Title_49 == null)) { (this.__Title_49 = new import5.Title(this.parent.get(import5.DOCUMENT))); }
    return this.__Title_49;
  }
  get _ɵi_50():import6.ɵi {
    if ((this.__ɵi_50 == null)) { (this.__ɵi_50 = new import6.ɵi()); }
    return this.__ɵi_50;
  }
  get _BrowserXhr_51():import7.BrowserXhr {
    if ((this.__BrowserXhr_51 == null)) { (this.__BrowserXhr_51 = new import7.BrowserXhr()); }
    return this.__BrowserXhr_51;
  }
  get _ResponseOptions_52():import7.BaseResponseOptions {
    if ((this.__ResponseOptions_52 == null)) { (this.__ResponseOptions_52 = new import7.BaseResponseOptions()); }
    return this.__ResponseOptions_52;
  }
  get _XSRFStrategy_53():any {
    if ((this.__XSRFStrategy_53 == null)) { (this.__XSRFStrategy_53 = import7.ɵb()); }
    return this.__XSRFStrategy_53;
  }
  get _XHRBackend_54():import7.XHRBackend {
    if ((this.__XHRBackend_54 == null)) { (this.__XHRBackend_54 = new import7.XHRBackend(this._BrowserXhr_51,this._ResponseOptions_52,this._XSRFStrategy_53)); }
    return this.__XHRBackend_54;
  }
  get _RequestOptions_55():import7.BaseRequestOptions {
    if ((this.__RequestOptions_55 == null)) { (this.__RequestOptions_55 = new import7.BaseRequestOptions()); }
    return this.__RequestOptions_55;
  }
  get _Http_56():any {
    if ((this.__Http_56 == null)) { (this.__Http_56 = import7.ɵc(this._XHRBackend_54,this._RequestOptions_55)); }
    return this.__Http_56;
  }
  createInternal():import1.AppModule {
    this._ɵa_0 = import2.ɵd(this.parent.get(import2.Router,(null as any)));
    this._ErrorHandler_1 = import5.ɵa();
    this._ɵg_2 = new import2.ɵg(this);
    this._NgProbeToken_3 = [import2.ɵb()];
    this._APP_INITIALIZER_4 = [
      import2.ɵh(this._ɵg_2),
      import0.ɵo,
      import5.ɵc(this.parent.get(import5.NgProbeToken,(null as any)),this._NgProbeToken_3)
    ]
    ;
    this._ApplicationInitStatus_5 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_4);
    this._ɵf_6 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_5);
    this._ApplicationRef_7 = this._ɵf_6;
    this._UrlSerializer_8 = new import2.DefaultUrlSerializer();
    this._RouterOutletMap_9 = new import2.RouterOutletMap();
    this._ROUTER_CONFIGURATION_10 = {};
    this._LocationStrategy_11 = import2.ɵc(this.parent.get(import3.PlatformLocation),this.parent.get(import3.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_10);
    this._Location_12 = new import3.Location(this._LocationStrategy_11);
    this._Compiler_13 = new import0.Compiler();
    this._NgModuleFactoryLoader_14 = new import0.SystemJsNgModuleLoader(this._Compiler_13,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
        this._ROUTES_15 = [[{
          path: '',
          loadChildren: '../dashboard/dashboard.module#DashboardModule'
        }
    ]];
    this._Router_16 = import2.ɵe(this._ApplicationRef_7,this._UrlSerializer_8,this._RouterOutletMap_9,this._Location_12,this,this._NgModuleFactoryLoader_14,this._Compiler_13,this._ROUTES_15,this._ROUTER_CONFIGURATION_10,this.parent.get(import2.UrlHandlingStrategy,(null as any)),this.parent.get(import2.RouteReuseStrategy,(null as any)));
    this._RouterModule_17 = new import2.RouterModule(this._ɵa_0,this._Router_16);
    this._RouteApplicationModule_18 = new import4.RouteApplicationModule();
    this._CommonModule_19 = new import3.CommonModule();
    this._ApplicationModule_20 = new import0.ApplicationModule(this._ApplicationRef_7);
    this._BrowserModule_21 = new import5.BrowserModule(this.parent.get(import5.BrowserModule,(null as any)));
    this._ɵba_22 = new import6.ɵba();
    this._FormsModule_23 = new import6.FormsModule();
    this._HttpModule_24 = new import7.HttpModule();
    this._AppModule_25 = new import1.AppModule();
    return this._AppModule_25;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.ɵa)) { return this._ɵa_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import2.ɵg)) { return this._ɵg_2; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_3; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_4; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import0.ɵf)) { return this._ɵf_6; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_7; }
    if ((token === import2.UrlSerializer)) { return this._UrlSerializer_8; }
    if ((token === import2.RouterOutletMap)) { return this._RouterOutletMap_9; }
    if ((token === import2.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_10; }
    if ((token === import3.LocationStrategy)) { return this._LocationStrategy_11; }
    if ((token === import3.Location)) { return this._Location_12; }
    if ((token === import0.Compiler)) { return this._Compiler_13; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_14; }
    if ((token === import2.ROUTES)) { return this._ROUTES_15; }
    if ((token === import2.Router)) { return this._Router_16; }
    if ((token === import2.RouterModule)) { return this._RouterModule_17; }
    if ((token === import4.RouteApplicationModule)) { return this._RouteApplicationModule_18; }
    if ((token === import3.CommonModule)) { return this._CommonModule_19; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_20; }
    if ((token === import5.BrowserModule)) { return this._BrowserModule_21; }
    if ((token === import6.ɵba)) { return this._ɵba_22; }
    if ((token === import6.FormsModule)) { return this._FormsModule_23; }
    if ((token === import7.HttpModule)) { return this._HttpModule_24; }
    if ((token === import1.AppModule)) { return this._AppModule_25; }
    if ((token === import2.ActivatedRoute)) { return this._ActivatedRoute_26; }
    if ((token === import2.NoPreloading)) { return this._NoPreloading_27; }
    if ((token === import2.PreloadingStrategy)) { return this._PreloadingStrategy_28; }
    if ((token === import2.RouterPreloader)) { return this._RouterPreloader_29; }
    if ((token === import2.PreloadAllModules)) { return this._PreloadAllModules_30; }
    if ((token === import2.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_31; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_32; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_33; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_34; }
    if ((token === import0.APP_ID)) { return this._APP_ID_35; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_36; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_37; }
    if ((token === import5.DomSanitizer)) { return this._DomSanitizer_38; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_39; }
    if ((token === import5.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_40; }
    if ((token === import5.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_41; }
    if ((token === import5.EventManager)) { return this._EventManager_42; }
    if ((token === import5.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_43; }
    if ((token === import5.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_44; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_45; }
    if ((token === import5.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_46; }
    if ((token === import0.Testability)) { return this._Testability_47; }
    if ((token === import5.Meta)) { return this._Meta_48; }
    if ((token === import5.Title)) { return this._Title_49; }
    if ((token === import6.ɵi)) { return this._ɵi_50; }
    if ((token === import7.BrowserXhr)) { return this._BrowserXhr_51; }
    if ((token === import7.ResponseOptions)) { return this._ResponseOptions_52; }
    if ((token === import7.XSRFStrategy)) { return this._XSRFStrategy_53; }
    if ((token === import7.XHRBackend)) { return this._XHRBackend_54; }
    if ((token === import7.RequestOptions)) { return this._RequestOptions_55; }
    if ((token === import7.Http)) { return this._Http_56; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_6.ngOnDestroy();
    (this.__RouterPreloader_29 && this._RouterPreloader_29.ngOnDestroy());
    (this.__ɵDomSharedStylesHost_43 && this._ɵDomSharedStylesHost_43.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYWNoZXJudXNoZXZpY2gvUHJvamVjdHMvUGVyc29uYWwvQW5ndWxhcjJ2MS9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9hY2hlcm51c2hldmljaC9Qcm9qZWN0cy9QZXJzb25hbC9Bbmd1bGFyMnYxL3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
